# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 247736fdfbc67d30fce637622240e74bb34f91a7b0377714db9883fffb529f89de3817da2ec87630365874c42a2175ae1cbd1a6d8e27f12fba5564308f339bdc

test:
  secret_key_base: 4ffc10cb96ab504daa8484f94e77a5ee455052500c3d2d2b176c38afffafe5c2e115bc55ff88d2a2ceb39132a3489989cca1fec72302550d87300217bd1e16cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
